export default {
	COUNTRIES_LOAD_START: "COUNTRIES_LOAD_START",
	COUNTRIES_LOAD_SUCCESS: "COUNTRIES_LOAD_SUCCESS",
	COUNTRIES_LOAD_ERROR: "COUNTRIES_LOAD_ERROR",

	COUNTRY_BY_NAME_LOAD_START: "COUNTRY_BY_NAME_LOAD_START",
	COUNTRY_BY_NAME_LOAD_SUCCESS: "COUNTRY_BY_NAME_LOAD_SUCCESS",
	COUNTRY_BY_NAME_LOAD_ERROR: "COUNTRY_BY_NAME_LOAD_ERROR",

	COUNTRIES_BY_REGION: "COUNTRIES_BY_REGION",

	SELECTED_COUNTRY: "SELECTED_COUNTRY",
};